### ISSUE TITLE
React-Native/Sunmi D2 Mini

### ISSUE THREAD

**Issue by davi-sant** [TecToy-Automacao/React-Native#2]
Olá, tenho uma duvida referente a inicialização de teste usando a base de código do <b>React Native</b>, usando app de exemplo [d2mini]. minha duvida seria qual próximo passo a ser dado,  visto que as configurações conforme descrito no <b>Readme</b> do projeto já foram feitas.

```
local.properties -> "sdk.dir = C:\Users\davis\AppData\Local\Android\Sdk";
```
```js
   It4rModule(ReactApplicationContext context) {
        super(context);
        tecToy = new TecToy(Dispositivo.D2_MINI, context);

    }
```

Importante mencionar que ao tentar exultar uma ação no app de exemplo eu recebo um `ERROR`.
```Error
 ERROR  TypeError: null is not an object (evaluating 'It4rModule.printEvent')
```

para finalizar gostaria de saber como posso está resolvendo esse possível `error` e posteriormente testar o app de exemplo no equipamento D2 MINI. Obrigado.

**Comment by cristiano-linvix** [comment]
Bom dia Davi, recomendo que você veja [este repositório](https://github.com/linvix-sistemas/react-native-tectoysunmisdk), não é oficial, mas já estou utilizando ele em produção, e tem os recursos principais disponíveis.

**Comment by dopidaniel** [comment]
Se você conseguir consumir um .JAR, pode também tentar essa opção:
https://github.com/TecToy-Automacao/Java/tree/master/jar/Sunmi/Printer

**Comment by davi-sant** [comment]
> Bom dia Davi, recomendo que você veja [este repositório](https://github.com/linvix-sistemas/react-native-tectoysunmisdk), não é oficial, mas já estou utilizando ele em produção, e tem os recursos principais disponíveis.

-------------------------------------//-----------------------------------------------------------
Boa vou testar, so mais uma duvida dando uma olhada no readme do seu projeto vi que tinhas uns rooks que te dava acesso a algumas funções do equipamento poderia me informar onde consumo esse conteúdo visto que o equipamento no qual seu código esta tendo como base é diferente do meu, ou os hooks é compatíveis com ambos os equipamentos?

**Comment by davi-sant** [comment]
> Se você conseguir consumir um .JAR, pode também tentar essa opção: https://github.com/TecToy-Automacao/Java/tree/master/jar/Sunmi/Printer

Até seria uma boa, mais infelizmente não possou conhecimentos em Java.

**Comment by cristiano-linvix** [comment]
> > Bom dia Davi, recomendo que você veja [este repositório](https://github.com/linvix-sistemas/react-native-tectoysunmisdk), não é oficial, mas já estou utilizando ele em produção, e tem os recursos principais disponíveis.
> 
> -------------------------------------//----------------------------------------------------------- Boa vou testar, so mais uma duvida dando uma olhada no readme do seu projeto vi que tinhas uns rooks que te dava acesso a algumas funções do equipamento poderia me informar onde consumo esse conteúdo visto que o equipamento no qual seu código esta tendo como base é diferente do meu, ou os hooks é compatíveis com ambos os equipamentos?

Qual o hook?

No código nativo ele utiliza os recursos disponibilizados pela Sunmi.

Você precisa ver os status retornados pelo dispositivo, no manual da Sunmi.

Aqui testei em alguns dispositivos e nos que estão ali na lista, funcionaram.
